// Board catalogue. Two boards share one rule shape; `setBoard` swaps the live
// exports so the engine and renderer pick up the chosen set.
const RENT_MULT = [1, 5, 15, 43, 58, 72];

function prop(groups, name, group, price) {
  const base = Math.max(2, Math.round(price / 12 / 2) * 2);
  return {
    kind: 'property', name, group, price,
    rent: RENT_MULT.map(m => Math.round(base * m / 2) * 2),
    houseCost: groups[group].houseCost,
  };
}

/* ---------------- 怡保美食 (Ipoh local food) ----------------
   摊位与老字号名称取自公开的怡保美食报导。*/
const IPOH_GROUPS = [
  { name: '白咖啡·旧街场', color: 0x9c6b42, houseCost: 50 },
  { name: '芽菜鸡·高温街', color: 0xd9b23c, houseCost: 50 },
  { name: '河粉面食', color: 0xd97a3c, houseCost: 100 },
  { name: '酿豆腐·大树脚', color: 0x74a83f, houseCost: 100 },
  { name: '糖水街', color: 0xd44f6e, houseCost: 150 },
  { name: '粥粉面·体育馆', color: 0x4a9bb5 , houseCost: 150 },
  { name: '甜品', color: 0x8a63c4, houseCost: 200 },
  { name: '伴手礼', color: 0x2f4858, houseCost: 200 },
];

const ipoh = {
  id: 'ipoh', name: '怡保美食', blurb: '一张桌、一碗河粉、一杯白咖啡。排队是本地传统。',
  currency: 'RM', groups: IPOH_GROUPS,
  labels: {
    start: '开市·饮早茶', jail: '排长龙', rest: '茶室歇脚',
    chance: '食神有话说', ledger: '肚子公告',
    house: '一张桌', houses: '张桌', hotel: '分店',
    jailLine: '被人潮困在队伍里。',
    jailDetail: '排三轮，或掷出对子插队成功。',
    startDetail: '开市红包，照收。',
    taxDetail: '交给市政局，不必问收据。',
    restLine: '在茶室歇脚，叫了杯白咖啡。',
    visitLine: '经过长龙，看一眼就走。',
    winLine: '吃遍全怡保',
    winSub: '其他人都已经吃到破产。',
    buildHint: '同色摊位全买下，才能加桌，再开分店。',
    buyDetail: '摊位待顶。要不要接手？',
    newsTitle: '街头消息',
    ui: {
      forSale: '待顶', paymentDue: '要付钱', moneyIn: '进帐', headsUp: '注意',
      card: '抽卡', buyFor: n => '顶下 ' + n, pay: n => '付 ' + n,
      collect: n => '收 ' + n, understood: '知道了', no: '不要',
      botBuys: n => '电脑顶下了，' + n + '。', botPasses: '电脑不要。',
      passing: n => '路过' + n, landedOn: n => '走到' + n,
      rentAt: n => n + ' 的桌租', paidTo: n => '付给 ' + n,
      folded: n => n + ' 吃到破产', foldedDetail: '摊位全数归还。',
      noPay: '没钱发了', noPayDetail: '快打模式：开市不再派钱。',
      unstuckTitle: '局面卡住了', unstuckDetail: '这一轮重新开始。',
      logFreed: n => n + ' 掷出对子，插队成功。',
      logFee: (n, f) => n + ' 付了 ' + f + '，下一轮才能走。',
      logStays: (n, t) => n + ' 还在排队（剩 ' + t + ' 轮）。',
      logPass: (n, c) => n + ' 路过开市，领 ' + c + '。',
      logDry: n => n + ' 路过开市，红包已经派完。',
      logBroke: (n, t) => n + ' 顶不起 ' + t + '。',
      logRent: (n, c, o, t) => n + ' 在 ' + t + ' 付了 ' + c + ' 给 ' + o + '。',
      logOwn: (n, t) => n + ' 坐在自己的 ' + t + '。',
      logTax: (t, n, c) => t + '：' + n + ' 付 ' + c + '。',
      logLand: (n, c) => n + ' 走到开市，领 ' + c + '。',
      logLandDry: n => n + ' 走到开市，什么都没领到。',
      logBuys: (n, t, c) => n + ' 顶下 ' + t + '，' + c + '。',
      logDeclines: (n, t) => n + ' 不要 ' + t + '。',
      logBuilds: (n, h, t) => n + ' 在 ' + t + ' ' + (h === '分店' ? '开了分店' : '加了' + h) + '。',
      logSells: (n, t) => n + ' 卖掉 ' + t + ' 的一张桌。',
      logOut: n => n + ' 吃到破产，退出。',
      logDoubles: n => n + ' 掷出对子，再来一轮。',
      roll: '掷骰', rolling: '掷…', rolled: '掷过了', bot: '电脑', endTurn: '换人', camera: '镜头', build: '加桌',
      roadAhead: '前面十格', newGame: '再来一局', paidTo: '付给',
      baseRent: '基本租金', fullSet: '（整组 ×2）',
      withHouses: n => '加' + n + '张桌', withHotel: '开分店',
      unclaimed: '未顶', heldBy: n => n + ' 的摊', buildCost: '加桌费',
      transit: '夜市·美食中心', utility: '公共', close: '关掉',
      nHeld: n => '持 ' + n + ' 个', oneHeld: '持一个', bothHeld: '持两个',
      deedCount: n => n + ' 个摊', inJail: '排队中',
      nowPlaying: '现在轮到', onTile: '在', changeBoard: '换张板',
      buildTitle: '加桌 — 同色收齐才行',
      roadFrom: n => '从 ' + n + ' 起', roadCount: n => '只看到 ' + n + ' 格',
      landToBuy: '走到这格才能顶。', empty: '空桌', restart: '再来一局',
      follow: '跟随', overview: '全景', victory: '封神', rapid: '快打',
      startCash: n => '本钱 ' + n, turnOf: '轮到', total: '合共',
      tabPlayers: '玩家', tabRoad: '前面十格', tabLog: '消息',
      tileStart: '领 RM200', tileJail: '路过看看', tileRest: '歇一歇', tileGoJail: '直接去排队',
      tilePay: '付 ',
    },
  },
  centre: 'skyline',
  tiles: g => [
    { kind: 'start', name: '开市·饮早茶' },
    prop(g, '南香茶餐室', 0, 60),
    { kind: 'ledger', name: '肚子公告' },
    prop(g, '天津茶室', 0, 60),
    { kind: 'tax', name: '停车罚单', amount: 200 },
    { kind: 'pier', name: '新街场夜市', price: 200 },
    prop(g, '安记芽菜鸡', 1, 100),
    { kind: 'chance', name: '食神有话说' },
    prop(g, '老黄芽菜鸡', 1, 100),
    prop(g, '高温街芽菜鸡', 1, 120),
    { kind: 'jail', name: '排长龙' },
    prop(g, '天津鸡丝河粉', 2, 140),
    { kind: 'works', name: '石灰山泉水', price: 150 },
    prop(g, '德记月光河', 2, 140),
    prop(g, '休罗街客家面', 2, 160),
    { kind: 'pier', name: '糖水街', price: 200 },
    prop(g, '忠记大树头', 3, 180),
    { kind: 'ledger', name: '肚子公告' },
    prop(g, '四十年大树脚', 3, 180),
    prop(g, '兵如港炸料粉', 3, 200),
    { kind: 'rest', name: '茶室歇脚' },
    prop(g, '长记牛腩面', 4, 220),
    { kind: 'chance', name: '食神有话说' },
    prop(g, '猪杂粥摊', 4, 220),
    prop(g, '杂果雪冰', 4, 240),
    { kind: 'pier', name: '体育馆美食中心', price: 200 },
    prop(g, '辉记鱼头米粉', 5, 260),
    prop(g, '咖喇面档', 5, 260),
    { kind: 'works', name: '旧街场咖啡厂', price: 150 },
    prop(g, '亚三叻沙档', 5, 280),
    { kind: 'gotojail', name: '被叫去排队' },
    prop(g, '黄记豆腐花', 6, 300),
    prop(g, '甘榜煎蕊', 6, 300),
    { kind: 'ledger', name: '肚子公告' },
    prop(g, '天津焦糖炖蛋', 6, 320),
    { kind: 'pier', name: '兵如港巴刹', price: 200 },
    { kind: 'chance', name: '食神有话说' },
    prop(g, '新荣香咖椰角', 7, 350),
    { kind: 'tax', name: '咖啡钱', amount: 100 },
    prop(g, '淡汶香饼家', 7, 400),
  ],
  chance: [
    { text: '一早开市，人还没到你已到。回到开市格，领 RM200。', move: 0 },
    { text: '你在网上发了一张河粉照，爆红。收 RM150。', cash: 150 },
    { text: '桌子摇了三年该修了：每张桌 RM25，每间分店 RM100。', repairs: [25, 100] },
    { text: '听说香饼刚出炉。直奔淡汶香饼家。', move: 39 },
    { text: '你插队被抓。去排长龙。', jail: true },
    { text: '走错巷子，倒退三格。', back: 3 },
    { text: '你赢了「谁最会吃」比赛。收 RM100。', cash: 100 },
    { text: '打包三十盒还要加钱：付 RM75。', cash: -75 },
    { text: '夜市开档了，前往糖水街。', move: 15 },
    { text: '朋友替你排到位子，前往天津鸡丝河粉。', move: 11 },
    { text: '你跟一颗椰子单挑，输了：付 RM20。', cash: -20, act: 'attack-melee-right' },
    { text: '你一脚踢好了茶室的风扇，老板请你吃：收 RM60。', cash: 60, act: 'attack-kick-right' },
    { text: '你抢到最后一份咖椰角，全场鼓掌：收 RM40。', cash: 40, act: 'interact-right' },
  ],
  ledger: [
    { text: '你把杯子还了，拿回押金 RM50。', cash: 50 },
    { text: '姑妈说你瘦了，塞给你 RM100。', cash: 100 },
    { text: '摊位年费到期：付 RM50。', cash: -50 },
    { text: '算错帐，多收了你的，退回 RM200。', cash: 200 },
    { text: '吃太辣看医生：付 RM50。', cash: -50 },
    { text: '卫生局突击检查：每张桌 RM40，每间分店 RM115。', repairs: [40, 115] },
    { text: '你占位太久被请走。去排长龙。', jail: true },
    { text: '回到开市格，再喝一杯。', move: 0 },
    { text: '油钱补贴下来了：收 RM75。', cash: 75 },
    { text: '整桌你请：付 RM100。', cash: -100 },
    { text: '你跟一只蚊子搏斗九分钟，还是输：付 RM30。', cash: -30, act: 'attack-melee-left' },
    { text: '你踹了一脚停车闸门，它开了，也没人收钱：收 RM80。', cash: 80, act: 'attack-kick-left' },
    { text: '你手滑打翻整杯白咖啡：付 RM45。', cash: -45, act: 'emote-no' },
  ],
};

/* ---------------- Jalan Malaysia ---------------- */
const MY_GROUPS = [
  { name: 'Melaka', color: 0x9b5fb0, houseCost: 50 },
  { name: 'Ipoh', color: 0x63b8dd, houseCost: 50 },
  { name: 'Penang', color: 0xe08a3c, houseCost: 100 },
  { name: 'Johor', color: 0xd44a4a, houseCost: 100 },
  { name: 'Langkawi', color: 0xe8b93a, houseCost: 150 },
  { name: 'Sabah & Sarawak', color: 0x3fa06a, houseCost: 150 },
  { name: 'Tanah Tinggi', color: 0x3f74c4, houseCost: 200 },
  { name: 'Kuala Lumpur', color: 0x27354f, houseCost: 200 },
];

const malaysia = {
  id: 'malaysia', name: 'Jalan Malaysia', blurb: 'Kampung to KLCC — states, highlands and night markets.',
  currency: 'RM', groups: MY_GROUPS,
  labels: {
    start: 'Mula', jail: 'Balai Polis', rest: 'Pasar Malam',
    chance: 'Rezeki', ledger: 'Peti Surat',
    house: 'rumah', houses: 'rumah', hotel: 'hotel',
    jailLine: 'is sent to the Balai Polis.',
    jailDetail: 'Three turns, or roll doubles to leave early.',
    startDetail: 'Salary collected at Mula.',
    taxDetail: 'Paid to the Lembaga Hasil.',
    restLine: 'stops for supper at the Pasar Malam.',
    visitLine: 'is just visiting the Balai Polis.',
    winLine: 'owns the whole jalan',
    winSub: 'Every other player has folded.',
    buildHint: 'Own every lot in a colour set to build rumah, then a hotel.',
    buyDetail: 'Unclaimed. Take the lot now, or leave it on the market.',
    newsTitle: 'Berita',
  },
  centre: 'tower',
  tiles: g => [
    { kind: 'start', name: 'Mula' },
    prop(g, 'Jonker Street', 0, 60),
    { kind: 'ledger', name: 'Peti Surat' },
    prop(g, 'Stadthuys', 0, 60),
    { kind: 'tax', name: 'Cukai Pendapatan', amount: 200 },
    { kind: 'pier', name: 'KLIA', price: 200 },
    prop(g, 'Kellie’s Castle', 1, 100),
    { kind: 'chance', name: 'Rezeki' },
    prop(g, 'Gunung Lang', 1, 100),
    prop(g, 'Kek Lok Tong', 1, 120),
    { kind: 'jail', name: 'Balai Polis' },
    prop(g, 'Gurney Drive', 2, 140),
    { kind: 'works', name: 'Tenaga Nasional', price: 150 },
    prop(g, 'Armenian Street', 2, 140),
    prop(g, 'Batu Ferringhi', 2, 160),
    { kind: 'pier', name: 'Penang Airport', price: 200 },
    prop(g, 'Danga Bay', 3, 180),
    { kind: 'ledger', name: 'Peti Surat' },
    prop(g, 'Jalan Tan Hiok Nee', 3, 180),
    prop(g, 'Puteri Harbour', 3, 200),
    { kind: 'rest', name: 'Pasar Malam' },
    prop(g, 'Pantai Cenang', 4, 220),
    { kind: 'chance', name: 'Rezeki' },
    prop(g, 'Kuah Town', 4, 220),
    prop(g, 'Sky Bridge', 4, 240),
    { kind: 'pier', name: 'Kota Kinabalu Airport', price: 200 },
    prop(g, 'Kota Kinabalu', 5, 260),
    prop(g, 'Kuching Waterfront', 5, 260),
    { kind: 'works', name: 'Air Selangor', price: 150 },
    prop(g, 'Mulu Caves', 5, 280),
    { kind: 'gotojail', name: 'Pergi ke Balai' },
    prop(g, 'Fraser’s Hill', 6, 300),
    prop(g, 'Cameron Highlands', 6, 300),
    { kind: 'ledger', name: 'Peti Surat' },
    prop(g, 'Genting Highlands', 6, 320),
    { kind: 'pier', name: 'Kuching Airport', price: 200 },
    { kind: 'chance', name: 'Rezeki' },
    prop(g, 'Bukit Bintang', 7, 350),
    { kind: 'tax', name: 'Cukai Perkhidmatan', amount: 100 },
    prop(g, 'KLCC', 7, 400),
  ],
  chance: [
    { text: 'Balik kampung. Move to Mula and collect RM200.', move: 0 },
    { text: 'Durian season windfall: collect RM150.', cash: 150 },
    { text: 'Monsoon repairs: pay RM25 per rumah, RM100 per hotel.', repairs: [25, 100] },
    { text: 'Penthouse viewing at KLCC. Advance there.', move: 39 },
    { text: 'Saman tak bayar. Go to the Balai Polis.', jail: true },
    { text: 'Wrong exit on the highway. Back three tiles.', back: 3 },
    { text: 'Toll rebate: collect RM100.', cash: 100 },
    { text: 'Parking summons: pay RM75.', cash: -75 },
    { text: 'Flight from Penang Airport. Advance there.', move: 15 },
    { text: 'Supper at Gurney Drive. Advance there.', move: 11 },
    { text: "You attack a coconut with your bare hands. It wins: pay RM20.", cash: -20, act: 'attack-melee-right' },
    { text: "One well-aimed kick fixes the kedai fan. Free supper: collect RM60.", cash: 60, act: 'attack-kick-right' },
  ],
  ledger: [
    { text: 'Duit raya from the family: collect RM50.', cash: 50 },
    { text: 'ASB dividend: collect RM100.', cash: 100 },
    { text: 'Road tax and insurance: pay RM50.', cash: -50 },
    { text: 'Tax refund from Hasil: collect RM200.', cash: 200 },
    { text: 'Clinic visit: pay RM50.', cash: -50 },
    { text: 'Renovation quit rent: pay RM40 per rumah, RM115 per hotel.', repairs: [40, 115] },
    { text: 'Roadblock, papers not in order. Go to the Balai Polis.', jail: true },
    { text: 'Return to Mula.', move: 0 },
    { text: 'Kenduri contribution returned: collect RM75.', cash: 75 },
    { text: 'School fees for the year: pay RM100.', cash: -100 },
    { text: "You swat at a mosquito for nine minutes and lose: pay RM30.", cash: -30, act: 'attack-melee-left' },
    { text: "You kick the parking gate. It opens. Nobody charges you: collect RM80.", cash: 80, act: 'attack-kick-left' },
  ],
};

/* ---------------- Hustle City (satire board) ---------------- */
const HUS_GROUPS = [
  { name: 'Starter Flats', color: 0x9a8f86, houseCost: 50 },
  { name: 'Gig Economy', color: 0x6fb7dd, houseCost: 50 },
  { name: 'Open Plan', color: 0xe2803c, houseCost: 100 },
  { name: 'Wellness', color: 0x74c05a, houseCost: 100 },
  { name: 'Startupland', color: 0xe3b731, houseCost: 150 },
  { name: 'The Suburbs', color: 0x54a465, houseCost: 150 },
  { name: 'Crypto', color: 0x8a63c4, houseCost: 200 },
  { name: 'Old Money', color: 0x2d3c58, houseCost: 200 },
];

const hustle = {
  id: 'hustle', name: 'Hustle City', blurb: 'Rise and grind. Mostly grind. Rents are due Monday.',
  currency: '$', groups: HUS_GROUPS,
  labels: {
    start: 'Monday', jail: 'HR Mediation', rest: 'Lunch Break',
    chance: 'Vibes', ledger: 'Fine Print',
    house: 'a pod', houses: 'pods', hotel: 'a headquarters',
    jailLine: 'has been invited to a conversation with HR.',
    jailDetail: 'Three turns of mandatory reflection, or roll doubles to be reassigned.',
    startDetail: 'Payroll cleared, somehow.',
    taxDetail: 'Non-refundable. Obviously.',
    restLine: 'takes a full lunch break. Nobody notices.',
    visitLine: 'walks past HR without making eye contact.',
    winLine: 'wins the entire economy',
    winSub: 'Everyone else is pivoting to consulting.',
    buildHint: 'Own a whole colour set to build pods, then a headquarters nobody asked for.',
    buyDetail: 'On the market. Bold move either way.',
    newsTitle: 'The group chat',
  },
  centre: 'tower',
  tiles: g => [
    { kind: 'start', name: 'Monday' },
    prop(g, 'Windowless Studio', 0, 60),
    { kind: 'ledger', name: 'Fine Print' },
    prop(g, 'Convertible Sofa', 0, 60),
    { kind: 'tax', name: 'Convenience Fee', amount: 200 },
    { kind: 'pier', name: 'Replacement Bus', price: 200 },
    prop(g, 'Surge Pricing Zone', 1, 100),
    { kind: 'chance', name: 'Vibes' },
    prop(g, 'Five-Star Rating', 1, 100),
    prop(g, 'Unpaid Internship', 1, 120),
    { kind: 'jail', name: 'HR Mediation' },
    prop(g, 'Hot Desk', 2, 140),
    { kind: 'works', name: 'The Printer', price: 150 },
    prop(g, 'Standing Desk', 2, 140),
    prop(g, 'Glass Meeting Box', 2, 160),
    { kind: 'pier', name: 'Delayed Flight', price: 200 },
    prop(g, 'Mandatory Fun', 3, 180),
    { kind: 'ledger', name: 'Fine Print' },
    prop(g, 'Mindfulness App', 3, 180),
    prop(g, 'Ergonomic Chair', 3, 200),
    { kind: 'rest', name: 'Lunch Break' },
    prop(g, 'Series A', 4, 220),
    { kind: 'chance', name: 'Vibes' },
    prop(g, 'The Pivot', 4, 220),
    prop(g, 'Disruptive Kombucha', 4, 240),
    { kind: 'pier', name: 'Rescheduled Train', price: 200 },
    prop(g, 'Cul-de-Sac', 5, 260),
    prop(g, 'Two-Car Garage', 5, 260),
    { kind: 'works', name: 'The Group Chat', price: 150 },
    prop(g, 'Lawn of Judgement', 5, 280),
    { kind: 'gotojail', name: 'Referred to HR' },
    prop(g, 'Definitely Not a Scam', 6, 300),
    prop(g, 'To The Moon', 6, 300),
    { kind: 'ledger', name: 'Fine Print' },
    prop(g, 'Diamond Hands', 6, 320),
    { kind: 'pier', name: 'Overbooked Ferry', price: 200 },
    { kind: 'chance', name: 'Vibes' },
    prop(g, 'The Family Trust', 7, 350),
    { kind: 'tax', name: 'Legacy Admissions Fee', amount: 100 },
    prop(g, 'Generational Wealth', 7, 400),
  ],
  chance: [
    { text: 'It is Monday again. Go there and collect $200.', move: 0 },
    { text: 'You went viral for eleven minutes: collect $150.', cash: 150 },
    { text: 'Your pods need repainting: pay $25 each, $100 per headquarters.', repairs: [25, 100] },
    { text: 'You married into Generational Wealth. Advance there.', move: 39 },
    { text: 'Reply-all incident. Go to HR Mediation.', jail: true },
    { text: 'You misread the calendar invite. Back three tiles.', back: 3 },
    { text: 'Class-action settlement: collect $100.', cash: 100 },
    { text: 'Subscription you forgot to cancel: pay $75.', cash: -75 },
    { text: 'Your flight is delayed. Advance to Delayed Flight.', move: 15 },
    { text: 'Someone booked you a Hot Desk. Advance there.', move: 11 },
    { text: "You fight the printer. The printer is undefeated: pay $20.", cash: -20, act: 'attack-melee-right' },
    { text: "You kick the vending machine and two snacks fall out: collect $60.", cash: 60, act: 'attack-kick-right' },
  ],
  ledger: [
    { text: 'You returned the thing: collect $50.', cash: 50 },
    { text: 'An aunt believed in you: collect $100.', cash: 100 },
    { text: 'Annual subscription renews at a worse price: pay $50.', cash: -50 },
    { text: 'Clerical error in your favour. Say nothing. Collect $200.', cash: 200 },
    { text: 'Dentist. Pay $50 and do not skip flossing.', cash: -50 },
    { text: 'Surprise inspection: pay $40 per pod, $115 per headquarters.', repairs: [40, 115] },
    { text: 'Your badge no longer works. Go to HR Mediation.', jail: true },
    { text: 'Back to Monday.', move: 0 },
    { text: 'Expense report finally approved: collect $75.', cash: 75 },
    { text: 'You were volunteered for the offsite: pay $100.', cash: -100 },
    { text: "You punch the air during a standup. HR is notified: pay $30.", cash: -30, act: 'attack-melee-left' },
    { text: "You kick the server rack and the outage ends. Hero for a day: collect $80.", cash: 80, act: 'attack-kick-left' },
  ],
};

export const BOARDS = { ipoh, malaysia, hustle };

/* ---------------- live exports ---------------- */
export let BOARD = ipoh;
export let GROUPS = ipoh.groups.map((g, i) => ({ id: i, ...g }));
export let TILES = ipoh.tiles(GROUPS);
export let CHANCE = ipoh.chance;
export let LEDGER = ipoh.ledger;
export let LABELS = ipoh.labels;
export let CURRENCY = ipoh.currency;

export function setBoard(id) {
  const b = BOARDS[id] || ipoh;
  BOARD = b;
  GROUPS = b.groups.map((g, i) => ({ id: i, ...g }));
  TILES = b.tiles(GROUPS);
  CHANCE = b.chance;
  LEDGER = b.ledger;
  LABELS = b.labels;
  CURRENCY = b.currency;
  return b;
}

export const PIER_RENT = [25, 50, 100, 200];

export const PLAYER_COLORS = [
  { name: 'Coral', hex: 0xd6503e, css: '#d6503e' },
  { name: 'Cobalt', hex: 0x2f6f9e, css: '#2f6f9e' },
  { name: 'Saffron', hex: 0xd9a12a, css: '#d9a12a' },
  { name: 'Moss', hex: 0x4f8a55, css: '#4f8a55' },
];

export const START_CASH = 1500;        // standard
export const BETA_CASH = 300;          // beta default: 20%, to surface bankruptcies
export const PASS_START = 200;
export const JAIL_FEE = 50;
export const JAIL_TILE = 10;
